#!/usr/bin/env bash
# Usage: ./1-world_wide_web <domain> <subdomain>
# Display information about subdomains.
# custom dig output

domain_information () {
    line=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
get_info() {
  domain=$1
  if [ -z $2 ]
  then
    for sub in "www" "lb-01" "web-01" "web-02"
    do
      name="$sub.$1"
      record="$(dig +noall +answer $name)"
      echo "$record" | awk -v su="$sub" '{ printf "The subdomain %s is a %s record and points to %s\n", su, $4, $5}'
    done
  else
    name="$2.$1"
    record="$(dig +noall +answer $name)"
    echo "$record" | awk -v su="$2" '{ printf "The subdomain %s is a %s record and points to %s\n", su, $4, $5}'
  fi
}
