#!/usr/bin/env bash
# Configures a ufw firewall to block all incoming traffic
#+ except for TCP ports 22, 443 and 80.

apt-get install ufw
sed -i 's/IPV6=.*/IPV6=yes/' /etc/default/ufw
ufw disable
ufw enable
ufw default deny incoming
ufw default allow outgoing
ufw allow 22/tcp
ufw allow 443/tcp
ufw allow 80/tcp
# Check the status of ufw to make sure it is active by running:

sudo ufw status

# If ufw is not active, you can enable it by running:
suo ufw enable

# Set the default incoming policy to "deny" to block all incoming traffic by running:
sudo ufw default deny incomming

# Set the default outgoing policy to "allow" to allow  all outgoing traffic by running:
sudo ufw default allow outgoing

# Allow incoming traffic on TCP ports 22, 443, and 80 by running:

sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp

# Verify that the rules have been added by running:

sudo ufw show added

# Finally, enable ufw by running:
sudo ufw enable
